apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    version: 6
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      defaultDatabase: ${CLICKHOUSE_DATABASE}
      defaultTable: otel_traces
      username: ${CLICKHOUSE_USERNAME}
      protocol: http
      port: 8123
      secure: false
      logs:
        defaultDatabase: ${CLICKHOUSE_DATABASE}
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: latest
        filterTimeColumn: TimestampTime
        timeColumn: Timestamp
        levelColumn: SeverityText
        messageColumn: Body
        showLogLinks: false
      traces:
        defaultDatabase: ${CLICKHOUSE_DATABASE}
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: latest
        traceIdColumn: TraceId
        spanIdColumn: SpanId
        parentSpanIdColumn: ParentSpanId
        serviceNameColumn: ServiceName
        operationNameColumn: SpanName
        startTimeColumn: Timestamp
        durationColumn: Duration
        durationUnit: nanoseconds
        tagsColumn: SpanAttributes
        serviceTagsColumn: ResourceAttributes
        statusCodeColumn: StatusCode
        statusMessageColumn: StatusMessage
        traceEventsColumnPrefix: Events
        traceLinksColumnPrefix: Links
        showTraceLinks: true
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
