receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include:
      - /var/log/app/*.log
    start_at: beginning
    operators:
      - type: json_parser

processors:
  batch:

exporters:
  clickhouse:
    endpoint: ${env:CLICKHOUSE_DSN}
    database: ${env:CLICKHOUSE_DATABASE}
    username: ${env:CLICKHOUSE_USERNAME}
    password: ${env:CLICKHOUSE_PASSWORD}
    traces_table_name: otel_traces
    timeout: 5s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [clickhouse]
